### ISSUE TITLE
PRECISA DE CORREÇÃO

### ISSUE THREAD

**Issue by evssousa** [davitkblade/viagem-a-fernando-de-noronha#1]
Prestar atenção no nome dos repositórios, devem está **IGUAL** aos dos projetos.

**Comment by davitkblade** [comment]
CORRIGIDO

**Comment by evssousa** [comment]
O nome do arquivo "reserve sua viagem.html". O nome do arquivo não pode conter espaços, além de não ser esse o nome do arquivo.

**Comment by evssousa** [comment]
Erro 404.

**Comment by davitkblade** [comment]
ambos os erros foram corrigidos.
